### ISSUE TITLE
Map overlay issues

### ISSUE THREAD

**Issue by Akito01** [Xerbo/aptdec#10]
Everytime I use a map, I see "WARNING: Map is too short to cover entire image". When subsequently I open the generated file, the map overlay is mispositioned over the capture. Can you help me out? For example I use this syntax to create an MCIR file and use the map generated by wxmap: aptdec -i m -e tdc -m /home/pi/weather/Maps/NOAA1820201022-113709-map.png /home/pi/weather/RAW/NOAA1820201022-113709.wav

This is how the map should be positioned (generated with wxtoimg): https://i.imgur.com/dJeIuJy.png

And this is how aptdec does it: https://i.imgur.com/g98pDjh.png

What am I doing wrong? I really want to start using more aptdec because its faster and imho gives better results when it comes to the amount of noise.

Thank you very much!

**Comment by Xerbo** [comment]
Occasionally the algorithm that handles finding how to align the map screws up, its a fact of life when dealing with analog signals (WXtoImg has the same issue sometimes). You can use `-k` to manually adjust the map if you don't mind some trial and error.

**Comment by Akito01** [comment]
So far, in my case, not any map has been properly aligned by aptdec. They're all way off. Whereas wxtoimg very sometimes is just a milimeter off instead of half a continent.
I will keep using wxtoimg until the algorithm has been improved unfortunately.

**Comment by Xerbo** [comment]
Hopefully shouldn't be too to improve, since the alignment is still really basic at the moment.
https://github.com/Xerbo/aptdec/blob/7892869d399ab05d88cb0047734d99e92ff9fecf/src/dsp.c#L242-L246
It uses Doppler shift to figure out where the point in which the satellite reached peak elevation above the receiving station, which then corresponds to the middle row of the map.

Give me a couple of hours and I'll throw together a hotfix for it (and post the diff in this thread), which will be merged into master sometime in the future.

**Comment by Xerbo** [comment]
A bit of progress later, this one uses an average of 4 rows to make the decision of when the satellite is at its highest elevation above the receiver.

```diff
diff --git a/src/dsp.c b/src/dsp.c
index ef6ae91..c567863 100755
--- a/src/dsp.c
+++ b/src/dsp.c
@@ -238,9 +238,9 @@ int getpixelrow(float *pixelv, int nrow, int *zenith, int reset) {
 	lcorr = fir(&pixelv[2], Sync, SyncFilterLen - 2);
 	FreqLine = 1.0+((ecorr-lcorr) / corr / PixelLine / 4.0);
 
-	// Find the point in which ecorr and lcorr intercept
-	if(fabs(lcorr - ecorr) < minDoppler && fabs(fabs(lcorr - ecorr) - previous) < 10){
-		minDoppler = fabs(lcorr - ecorr);
+	double val = fabs(lcorr - ecorr)*0.25 + previous*0.75;
+	if(val < minDoppler && nrow > 10){
+		minDoppler = val;
 		*zenith = nrow;
 	}
 	previous = fabs(lcorr - ecorr);
```

1. Throw that into a file called `improve_map_alignment.diff`
2. `git pull`
3. `git apply improve_map_alignment.diff`

**Comment by Akito01** [comment]
Sorry for the delay. I have given this a try but I'm getting an error upon applying:
error: patch failed: src/dsp.c:238
error: src/dsp.c: patch does not apply

--edit-- Here is the error:
# git apply --reject improve_map_alignment.diff
```
Checking patch src/dsp.c...
error: while searching for:
        lcorr = fir(&pixelv[2], Sync, SyncFilterLen - 2);
        FreqLine = 1.0+((ecorr-lcorr) / corr / PixelLine / 4.0);

        // Find the point in which ecorr and lcorr intercept
        if(fabs(lcorr - ecorr) < minDoppler && fabs(fabs(lcorr - ecorr) - previous) < 10){
                minDoppler = fabs(lcorr - ecorr);
                *zenith = nrow;
        }
        previous = fabs(lcorr - ecorr);

error: patch failed: src/dsp.c:238
Applying patch src/dsp.c with 1 reject...
Rejected hunk #1.
```

**Comment by Akito01** [comment]
I've managed to apply the patch this time...but after rebuilding the binary the map is still like half a continent off.

**Comment by Xerbo** [comment]
Could you send me the audio from this pass, and the map. I can't really do any further troubleshooting without it.

**Comment by Akito01** [comment]
Sure, here is the audio: https://easyupload.io/zs58pg
and here is the map: https://easyupload.io/2tjsf2

This is a recording from tonight, and needs an offset of about -300.

**Comment by Xerbo** [comment]
Hmmm, when I ran it with the same patch I got this, which is pretty close. Could you send what command you are running.

![A screenshot of the results for me](https://user-images.githubusercontent.com/23143405/98487561-8bcf1d80-221b-11eb-9433-91efef0df6af.png)

**Comment by Akito01** [comment]
Sure, this is it:
```
# git clone https://github.com/Xerbo/aptdec.git
Cloning into 'aptdec'...
remote: Enumerating objects: 413, done.
remote: Counting objects: 100% (413/413), done.
remote: Compressing objects: 100% (290/290), done.
remote: Total 830 (delta 249), reused 261 (delta 117), pack-reused 417
Receiving objects: 100% (830/830), 867.44 KiB | 2.15 MiB/s, done.
Resolving deltas: 100% (515/515), done.

# cd aptdec/
# nano improve_map_alignment.diff
# mkdir build
# git pull
Already up to date.
# git apply improve_map_alignment.diff (timestamp of dsp.c has changed after this to current time)
# cd build/
# cmake -DCMAKE_BUILD_TYPE=Release ..
# make
```

Part of src/dsp.c looks like this after applying the patch:
```
       // Calculate the frequency offset
        ecorr = fir(pixelv, Sync, SyncFilterLen);
        corr = fir(&pixelv[1], Sync, SyncFilterLen - 1);
        lcorr = fir(&pixelv[2], Sync, SyncFilterLen - 2);
        FreqLine = 1.0+((ecorr-lcorr) / corr / PixelLine / 4.0);

        double val = fabs(lcorr - ecorr)*0.25 + previous*0.75;
        if(val < minDoppler && nrow > 10){
                minDoppler = val;
                *zenith = nrow;
        }
        previous = fabs(lcorr - ecorr);
```

**Comment by Xerbo** [comment]
I meant how you ran aptdec, something like `aptdec -i m -m pathtomap.png audio.wav`, although having that confirms that the patch was applied successfully.

**Comment by Akito01** [comment]
Yes exactly like that. However, trying out some stuff... I have come to the conclusion that the cropping of noise function make the map offset worse. My command of aptdec -i m -e dc -m /pathtomap.png /pathtoaudio.wav makes the map offset bigger.
Using only -m m -e d /pathtomap.wav /pathtoaudio.wav makes the offset more or less like you showed me in one of your latest answers. So, for me it seems that cropping the noise makes the map dislocation worse.

**Comment by Xerbo** [comment]
> I have come to the conclusion that the cropping of noise function make the map offset worse.

Oh crap, I completely forgot about that, that physically the rows from the start of the image from memory, and doesn't adjust the map alignment.

So, that's whats causing it, luckily this is an easy fix. Will get on this in a second.

**Comment by Akito01** [comment]
Yes now it works. Thanks!

Now I've never seen this before so I'm not sure if this is a newly introduced bug, or if I have just missed this... but for northbound captures the image needs to be flipped. The capture is being flipped indeed, but the map is not. Resulting in the map overlay being upside down on a flipped capture.

I think that is a fairly easy fix as well though.

Would you like for me to close this issue and open a new issue for this? Or is it ok to remain with this one?

**Comment by Xerbo** [comment]
Sorry for the delays, have been busy with other things... GOES-13 GVAR and Lucky-7 mainly. But yes, I will get on this *soon*.

**Comment by Xerbo** [comment]
wxmap support was removed in c754d5fb5760416cf9cf0b8faf262d2613885734
