### ISSUE TITLE
Image cropped left and right

### ISSUE THREAD

**Issue by Akito01** [Xerbo/aptdec#11]
I have just come to notice another issue that I hadn't noticed before... but after trying several recording I've come to realize this happens with every generated image: a large chunk of the left and right side of the image is cut off, compared with wxtoimg.
Clear example in these 2 images where a major part of England is cut off as well as part of Russia and Turkey.
The wxtoimg image (with England and Turkey):
[https://i.imgur.com/vrp0zLx.png](url)

The aptdec image (without England and Turkey):
[https://i.imgur.com/DlcIfFC.png](url)

**Comment by Akito01** [comment]
After testing some more, it's the 'crop telemetry' function that cuts it off. Removing this parameter will show England etc. again, but I was expecting to see the telemetry lines now which aren't visible.

So not cropping telemetry won't show the telemetry lines anyway.... cropping the telemetry will cut off some of land of the image.

**Comment by Xerbo** [comment]
Could you send me the audio from this pass, its kind of needed to troubleshoot. Also next time could you follow the issue template.

**Comment by Akito01** [comment]
Yes, here it is:
https://easyupload.io/ef91wf

And sorry, I wasn't aware of the template.
