### ISSUE TITLE
"‘A’ may be used uninitialized" when building with "-DCMAKE_BUILD_TYPE=Release"

### ISSUE THREAD

**Issue by the-gobleo-tinkerer** [Xerbo/aptdec#15]
**Describe the bug**
When building with `-DCMAKE_BUILD_TYPE=Release`, gcc 11.1.0 gives the following error:
```
In function ‘FactPiv’,
    inlined from ‘polyreg’ at /home/shuyuan/Build/aptdec/src/libs/reg.c:68:2:
/home/shuyuan/Build/aptdec/src/libs/reg.c:115:34: error: ‘A’ may be used uninitialized [-Werror=maybe-uninitialized]
  115 |         DET = DET * A[Row[N - 1]][N - 1];
      |                     ~~~~~~~~~~~~~^~~~~~~
/home/shuyuan/Build/aptdec/src/libs/reg.c: In function ‘polyreg’:
/home/shuyuan/Build/aptdec/src/libs/reg.c:23:16: note: ‘A’ declared here
   23 |         double A[DMAX][DMAX];   /* A */
      |                ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/apt.dir/build.make:132: CMakeFiles/apt.dir/src/libs/reg.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/apt.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

Clang 12.0.0 builds without errors. Also no error is given if the `-DCMAKE_BUILD_TYPE=Release` flag is not set.

**To Reproduce**
`git clone ...`
`cd aptdec`
`mkdir build`
`cd build`
`cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release ..`

**Expected behaviour**
The array `A` should be initialized or a compiler option should be included to suppress the error, so that aptdec can be built successfully.

**Build information**
Commit 794d69c9a7753feba4bd89cb037eac40cf6bbcd2,
Using CMake, GCC 11.1.0.

**Comment by Xerbo** [comment]
Fixed in 0c44daa
