### ISSUE TITLE
Code no longer compiles with MSVC

### ISSUE THREAD

**Issue by srcejon** [Xerbo/aptdec#20]
With the introduction of the complex data type, aptdec no longer compiles with MSVC, which is a shame, as the latest code can't be included in [SDRangel](https://github.com/f4exb/sdrangel/blob/master/plugins/channelrx/demodapt/readme.md)

It's possible to write a little abstraction layer, so complex types can be used both with gcc/clang/MSVC, see here as an example:

https://github.com/srcejon/codec2/blob/windows-freedv/src/compiler.h

Would you be open to a patch that used something along these lines?

**Comment by Xerbo** [comment]
~~https://learn.microsoft.com/en-us/cpp/c-runtime-library/complex-math-support?view=msvc-170 MSVC seems to have its own complex library, just different to POSIX, can you confirm?~~

EDIT: I have seen the link you have sent I will get on this right away

**Comment by Xerbo** [comment]
MSVC seems to implement all the POSIX complex functions and the `I` constant so in theory this should work

**Comment by srcejon** [comment]
Thanks. It's not necessary to add zenith back in, I can remove that SDRangel. It's the complex in the hilbert_transform that's the main problem.

**Comment by Xerbo** [comment]
This should be fixed, can you check?

**Comment by srcejon** [comment]
It compiles, thanks. Will try integrating it a little later on.

**Comment by srcejon** [comment]
Seems to work fine on Linux and Windows. Thanks.
