### ISSUE TITLE
Multi threaded decoder

### ISSUE THREAD

**Issue by Akito01** [Xerbo/aptdec#24]
Would it be possible to have aptdec be multi threaded?
Ideally with a parameter so we can indicate how many cores we would like to use for decoding (just like with the make command in the compiling process, eg. make -j2, -j3, -j4). This could potentially speed up generation of the images a lot.

**Comment by Xerbo** [comment]
Multi threading DSP involves a FIFO between steps which in some cases (aptdec probably being one) can actually reduce performence, you can try the `v2` branch that should be faster.
