### ISSUE TITLE
Segmentation Fault -aptdec -i t -s 18 2020-06-10-21-30-06-NOAA_18.wav

### ISSUE THREAD

**Issue by KiwiInNZ** [Xerbo/aptdec#3]
Code installed onto a Raspberry Pi 3, running latest fully patched Buster, using instructions for installing from https://github.com/Xerbo/aptdec.

Using the .wav file from a recent NOAA 18 pass over New Zealand:

[2020-06-10-21-30-06-NOAA_18.zip](https://github.com/Xerbo/aptdec/files/4767937/2020-06-10-21-30-06-NOAA_18.zip)

One of the examples for using aptdec from the README.md is:
`./aptdec -i t -s 18 gqrx_20200527_115730_137914960.wav`

Using the example .wav gives a segmentation fault.
```
./aptdec -i t -s 18 2020-06-10-21-30-06-NOAA_18.wav
Aptdec; (c) 2004-2009 Thierry Leconte F4DWV, Xerbo (xerbo@protonmail.com) 2019-2020
Input file: 2020-06-10-21-30-06-NOAA_18.wav
Input sample rate: 11025
Total rows: 1793
Channel A: 1 (visble)
Channel B: 4 (thermal-infrared)
Temperature... Done
Segmentation fault
```
The output file created is a zero length file:
`-rw-r--r-- 1 pi pi        0 Jun 12 12:33 2020-06-10-21-30-06-NOAA_18-t.png`

This .wav file processes well using wxtoimg, as seen at - https://kiwiweather.com/2020/06/10/2020-06-10-21-30-06-NOAA_18.html.

**Comment by Xerbo** [comment]
This is definitely interesting. It seems to be a problem with aptdec on ARM, it works fine on x86. I'll try it on a RasPi soon.

**Comment by Xerbo** [comment]
Should be fixed now, run `git pull && make` in the directory.
This was a simple case of me forgetting that something was a pointer, and not treating it as a pointer, but for some reason it didn't crash on x86.

**Comment by KiwiInNZ** [comment]
Tested this on the same Pi after the git pull and make using the same audio and it worked fine.
