### ISSUE TITLE
Adding map overlay - Segmentation fault

### ISSUE THREAD

**Issue by KiwiInNZ** [Xerbo/aptdec#5]
Same Pi / Buster combo with updated code from previous issue:

`aptdec -m 2020-06-10-21-30-06-NOAA_18-map.png 2020-06-10-21-30-06-NOAA_18.wavv`

![2020-06-10-21-30-06-NOAA_18-map](https://user-images.githubusercontent.com/51867737/84551324-59e78700-ad61-11ea-9df3-ce3db41a0f0b.png)
[2020-06-10-21-30-06-NOAA_18.zip](https://github.com/Xerbo/aptdec/files/4773517/2020-06-10-21-30-06-NOAA_18.zip)

```
pi@Beta:~/temp $ aptdec -m 2020-06-10-21-30-06-NOAA_18-map.png 2020-06-10-21-30-06-NOAA_18.wav
Aptdec; (c) 2004-2009 Thierry Leconte F4DWV, Xerbo (xerbo@protonmail.com) 2019-2020
Input file: 2020-06-10-21-30-06-NOAA_18.wav
Input sample rate: 11025
Total rows: 1793
Channel A: 1 (visble)
Channel B: 4 (thermal-infrared)
WARNING: Map is too short to cover entire image
Adding map overlay
Segmentation fault
```
Potential link to #4.

**Comment by Xerbo** [comment]
Yes, one of the warnings in #4 was partially to blame for this. I silenced the `-Wmissing-field-initializers` warnings (they're not important) to make actual useful warnings easier to see in future.

And thanks for reporting bugs instead of just ditching aptdec and continuing to use wxtoimg.
